# Advanced Indexing
- Returns copy of the data while in basic indexing we can get only view.
- Types-
    - Integer - will use integer as index
    - Boolean

In [1]:
import numpy as np

In [3]:
testArray = np.arange(1,10)
testArray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Here I want to access few elements like 2 5 and 9
# - Creates an array of index

In [6]:
arrayElementIndex = np.array([1,4,8])

In [7]:
arrayElementIndex

array([1, 4, 8])

In [8]:
testArray[arrayElementIndex]

array([2, 5, 9])

In [9]:
# Also you can create list of those indexes instead of array

In [12]:
testArray[[1,4,8]]

array([2, 5, 9])

### For Multidimensional Array

In [14]:
multiDimArray = np.array([[1,2,3],[4,5,6],[7,8,9]])
multiDimArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# for accessing the elements mention the index in order of row & column
# here I want to access element 4 and 7

multiDimArray[[1,2],[0,0]]

array([4, 7])

In [16]:
# access 1 and 9

multiDimArray[[0,2], [0,2]]

array([1, 9])

### Boolean 

In [18]:
boolArray = np.array([[1,2,-3],[-4,-5,6]])
boolArray

array([[ 1,  2, -3],
       [-4, -5,  6]])

In [19]:
boolArray[boolArray]

IndexError: index 2 is out of bounds for axis 0 with size 2