# Arithmetic Operation In Numpy Array
    - operation happens using element by element

In [1]:
import numpy as np

In [4]:
testArray = np.arange(1,6)
testArray

array([1, 2, 3, 4, 5])

In [5]:
testArray+2

array([3, 4, 5, 6, 7])

In [6]:
testArray-1.5

array([-0.5,  0.5,  1.5,  2.5,  3.5])

In [7]:
testArray/0.5

array([ 2.,  4.,  6.,  8., 10.])

In [8]:
testArray**2

array([ 1,  4,  9, 16, 25])

In [9]:
newArray = np.array([[1,2],[3,4]])
newArray

array([[1, 2],
       [3, 4]])

In [10]:
newArray+2

array([[3, 4],
       [5, 6]])

In [14]:
array1 = np.arange(1,6)
array1



array([1, 2, 3, 4, 5])

In [15]:
array2 = np.array([10,20,30,40,50])
array2

array([10, 20, 30, 40, 50])

In [16]:
array1+array2

array([11, 22, 33, 44, 55])

In [19]:
#Instead of operator we can use np functions for arithmetic operations like-
# - np.add(a,b)
# - np.subtract(a,b)
# - np.multiply(a,b)
# - np.divide(a,b)
    

In [21]:
sum = np.add(array1, array2)
sum

array([11, 22, 33, 44, 55])

In [23]:
subtract  = np.subtract(array1, array2)
subtract

array([ -9, -18, -27, -36, -45])