# Array Manipulation Part-2
   - transpose() - this will rearrange the dimension of an numpy array.
       - transpose function can transpose only 2,3..D array . if you use 1D array than there won;t b any changes
   - swapaxes  -- useful in 3d and 4d array

In [1]:
import numpy as np


In [2]:
help(np.transpose)

Help on function transpose in module numpy:

transpose(a, axes=None)
    Permute the dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : list of ints, optional
        By default, reverse the dimensions, otherwise permute the axes
        according to the values given.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    moveaxis
    argsort
    
    Notes
    -----
    Use `transpose(a, argsort(axes))` to invert the transposition of tensors
    when using the `axes` keyword argument.
    
    Transposing a 1-D array returns an unchanged view of the original array.
    
    Examples
    --------
    >>> x = np.arange(4).reshape((2,2))
    >>> x
    array([[0, 1],
           [2, 3]])
    
    >>> np.transpose(x)
    array([[0, 2],
           [1, 3]])
    
    >>> x = np.ones((1, 2, 3))
    >>> np.transpose(x, (1, 0, 2)).s

In [5]:
testArray = np.arange(1,11).reshape(5,2)
testArray

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [7]:
testArray.shape

(5, 2)

In [10]:
newTestArray = np.transpose(testArray)
newTestArray

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [11]:
newTestArray.shape

(2, 5)

In [13]:
#transpose happened in reversed order (5,2)---> (2,5)

In [14]:
# Using axes paramter 

In [15]:
newAxArray = np.arange(1,11).reshape(5,2)
newAxArray

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [17]:
np.transpose(newAxArray).shape

(2, 5)

In [19]:
np.transpose(newAxArray, axes=(1,0))

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [21]:
# we can use short form for transpose

In [26]:
array1 = np.array([1,2,3,4,5,6]).reshape(2,3)
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
array1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### swapaxes

In [28]:
help(np.swapaxes)

Help on function swapaxes in module numpy:

swapaxes(a, axis1, axis2)
    Interchange two axes of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis1 : int
        First axis.
    axis2 : int
        Second axis.
    
    Returns
    -------
    a_swapped : ndarray
        For NumPy >= 1.10.0, if `a` is an ndarray, then a view of `a` is
        returned; otherwise a new array is created. For earlier NumPy
        versions a view of `a` is returned only if the order of the
        axes is changed, otherwise the input array is returned.
    
    Examples
    --------
    >>> x = np.array([[1,2,3]])
    >>> np.swapaxes(x,0,1)
    array([[1],
           [2],
           [3]])
    
    >>> x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
    >>> x
    array([[[0, 1],
            [2, 3]],
           [[4, 5],
            [6, 7]]])
    
    >>> np.swapaxes(x,0,2)
    array([[[0, 4],
            [2, 6]],
           [[1, 5],
            [3, 7]]])



In [35]:
np.swapaxes(array1,1,0)

array([[1, 4],
       [2, 5],
       [3, 6]])