# Array Manipulation-1
   - reshape - without changing the data it changes the shape
   - resize - it will change the data of an array. np.resize() won;t change the original array but array.resize() alter the original array
   - flatten()
   - ravel()

In [1]:
import numpy as np

In [2]:
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

In [11]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [13]:
arr.shape

(6,)

In [19]:
b = np.reshape(arr, (3,2), order='F')
b

array([[0, 3],
       [1, 4],
       [2, 5]])

In [21]:
# Instead of np.reshape we can use arr.reshape also

b = arr.reshape((3,2))
b

array([[0, 1],
       [2, 3],
       [4, 5]])

### resize()

In [22]:
help(np.resize)

Help on function resize in module numpy:

resize(a, new_shape)
    Return a new array with the specified shape.
    
    If the new array is larger than the original array, then the new
    array is filled with repeated copies of `a`.  Note that this behavior
    is different from a.resize(new_shape) which fills with zeros instead
    of repeated copies of `a`.
    
    Parameters
    ----------
    a : array_like
        Array to be resized.
    
    new_shape : int or tuple of int
        Shape of resized array.
    
    Returns
    -------
    reshaped_array : ndarray
        The new array is formed from the data in the old array, repeated
        if necessary to fill out the required number of elements.  The
        data are repeated in the order that they are stored in memory.
    
    See Also
    --------
    ndarray.resize : resize an array in-place.
    
    Notes
    -----
    i.e. it does not apply interpolation/extrapolation.
    It fills the return array with the required 

In [23]:
arr = np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [27]:
np.resize(arr,(2,1))

array([[1],
       [2]])

### Flatten()
    - It will return the copy of an array containing same element. Also dimensions will be collapsed into 1 D.

In [31]:
testArray = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
testArray

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
testArray.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
testArray.flatten(order='F')

array([ 1,  7,  4, 10,  2,  8,  5, 11,  3,  9,  6, 12])

### ravel()
 - It copy the element if needed.

In [35]:
testArray

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [36]:
testArray.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
np.ravel(testArray)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Difference b/w flatten & ravel

In [38]:
#Flatten is a method of ndarray while ravle is a library level method.
#we can use like -> ndArray.flatten  & np.ravel() & ndarray.ravel()

#--> Flatten() returns copy of an original array while ravel provides view/refrence of an original array.