# Array Manipulation Part-4
   - insert()
   - append()

In [1]:
import numpy as np

In [2]:
array1= np.arange(1,11)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# Now insert elemnt 80 at index 3
np.insert(array1, 3, 80)

array([ 1,  2,  3, 80,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# If you want to insert multiple elements -
np.insert(array1, (2,5), 80)

array([ 1,  2, 80,  3,  4,  5, 80,  6,  7,  8,  9, 10])

### append()

In [5]:
help(np.append)

Help on function append in module numpy:

append(arr, values, axis=None)
    Append values to the end of an array.
    
    Parameters
    ----------
    arr : array_like
        Values are appended to a copy of this array.
    values : array_like
        These values are appended to a copy of `arr`.  It must be of the
        correct shape (the same shape as `arr`, excluding `axis`).  If
        `axis` is not specified, `values` can be any shape and will be
        flattened before use.
    axis : int, optional
        The axis along which `values` are appended.  If `axis` is not
        given, both `arr` and `values` are flattened before use.
    
    Returns
    -------
    append : ndarray
        A copy of `arr` with `values` appended to `axis`.  Note that
        `append` does not occur in-place: a new array is allocated and
        filled.  If `axis` is None, `out` is a flattened array.
    
    See Also
    --------
    insert : Insert elements into an array.
    delete : Delet

In [6]:
np.append(array1, 800)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 800])

In [10]:
a = np.array([[3,1],[2,4]])
a

array([[3, 1],
       [2, 4]])

In [13]:
b = np.array([9,8])

In [14]:
np.linalg.solve(a,b)

array([2.8, 0.6])