# Numerical Data Types-
Boolean, Integer, Unsigned Integer, Float, Complex

int32 - here 32 is the bit, so 1 byte = 8bit. 32/8 = 4 bit.

In [1]:
import numpy as np

In [9]:
testArray = np.zeros(3)
testArray
testArray.dtype

dtype('float64')

In [7]:
testArray = np.zeros(3, dtype=np.int8)
testArray

array([0, 0, 0], dtype=int8)

In [8]:
testArray.dtype

dtype('int8')

# Data type as functions()

-- can use character code also to mention the data type

In [15]:
test = np.float32(1)
test
test.dtype


dtype('float32')

In [21]:
test = np.array([3,2], dtype='f')
test

array([3., 2.], dtype=float32)

In [22]:
test = np.array([3,2], dtype='i')
test

array([3, 2], dtype=int32)

### We can change the type of an array using .astype()

In [26]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [27]:
a.dtype

dtype('float64')

In [33]:
#Now change the type of the element
aa = a.astype(int)

In [34]:
aa.dtype

dtype('int64')

In [36]:
# USing data type as an function.
aaa = np.int8(aa)
aaa

array([0, 0, 0, 0, 0], dtype=int8)