# Array
Create array from list or tuple

In [1]:
import numpy as np


In [2]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

In [12]:
newArr = np.array([1,2,3], ndmin=2)

In [13]:
newArr

array([[1, 2, 3]])

### Create an array

In [14]:
a = np.array([1,2,3])

In [15]:
a

array([1, 2, 3])

### Create an array with multi list

In [18]:
aa = np.array([[1,2,3],[4,5,6]])

In [19]:
aa

array([[1, 2, 3],
       [4, 5, 6]])

### Chnage the data type

In [20]:
aDataType = np.array([1,2,3], dtype='complex')

In [21]:
aDataType

array([1.+0.j, 2.+0.j, 3.+0.j])

### Create an using tuples()

In [23]:
tupelArray = np.array((1,2,3))

In [24]:
tupelArray

array([1, 2, 3])

In [26]:
tupelArray1 = np.array(((1,2,3),(4,5,6)))

In [27]:
tupelArray1

array([[1, 2, 3],
       [4, 5, 6]])

# Arange()
Creates Array of evenly spaced values.

In [28]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [29]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

####  Here I din't mentioned start value so by default it will take as 0

In [31]:
np.arange(3.0)

array([0., 1., 2.])

#### Using step

(start, stop, step)

In [35]:
np.arange(1,10,2)
#Here 1 is starting number, 10 is stop and 2 is step

array([1, 3, 5, 7, 9])

In [34]:
np.arange(15, dtype='complex')

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
       14.+0.j])

# Zeros()

In [36]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [41]:
np.zeros(5)
# default data types is float

array([0., 0., 0., 0., 0.])

In [42]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

### Multi dimensinal 

In [50]:
np.zeros([3,2], int)
#using list

array([[0, 0],
       [0, 0],
       [0, 0]])

In [48]:
np.zeros((2,3),int)
#Using tuple

array([[0, 0, 0],
       [0, 0, 0]])

In [52]:
np.zeros([3,4], order='F')

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Ones()

In [53]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [54]:
np.ones(3)

array([1., 1., 1.])

In [57]:
np.ones((2,3), int)

array([[1, 1, 1],
       [1, 1, 1]])

In [59]:
np.empty([3,4], dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# Linspace()

In [61]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [63]:
np.linspace(2,5,12)

array([2.        , 2.27272727, 2.54545455, 2.81818182, 3.09090909,
       3.36363636, 3.63636364, 3.90909091, 4.18181818, 4.45454545,
       4.72727273, 5.        ])

In [65]:
np.linspace(2,5,12, retstep=True)
#If retstep = True then. will get the difference also b/w the. numbers

(array([2.        , 2.27272727, 2.54545455, 2.81818182, 3.09090909,
        3.36363636, 3.63636364, 3.90909091, 4.18181818, 4.45454545,
        4.72727273, 5.        ]), 0.2727272727272727)

In [69]:
np.linspace(1,150, num=5, endpoint=False)
#include endpoint will use the 150, if set to false then won;t include 150

array([  1. ,  30.8,  60.6,  90.4, 120.2])

In [71]:
np.linspace(1,150, num=5, endpoint=False, retstep=True)

(array([  1. ,  30.8,  60.6,  90.4, 120.2]), 29.8)

In [73]:
np.linspace(1,10)
# Here default value of num is 50 so it will print 50 interval values.

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [76]:
np.linspace(1,10, num=4, dtype=int)
# Here directly you can write data type also like 'int'

array([ 1,  4,  7, 10])