# Slicing:
- If you want to retrieve collection of values.

In [1]:
import numpy as np

### 1-D array

In [6]:
dualChannel = np.array([1,20,13,44,25,16,7,8])

In [7]:
#If you want to print(access) all the elements
dualChannel[:]

array([ 1, 20, 13, 44, 25, 16,  7,  8])

In [8]:
#If you enter only end index
dualChannel[:3]

array([ 1, 20, 13])

In [9]:
# If you enter only start index
dualChannel[1:]

array([20, 13, 44, 25, 16,  7,  8])

In [10]:
# using start & end index
dualChannel[1:5]

array([20, 13, 44, 25])

### 2-D Array

In [14]:
# array_name[start:end:step, start:end:step] 1st part for row(i) and 2nd for columns(j)

![title](ArrayIndexing.png)

In [34]:
# from the above image access the element 4 & 6

testArray = np.array([[1,2],[3,4],[5,6]])

In [35]:
testArray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
testArray[1:, 1:]

array([[4],
       [6]])

In [38]:
newArray = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
newArray[1:, 1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [48]:
#Access based on the step

newArray[::, ::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])